flyway:
  datasource:
    hostname: "${postgresql_server}"
    port: "5432"
    database: ohdsi
    user: ohdsi

datasource:
  hostname: "${postgresql_server}"
  port: "5432"
  database: ohdsi
  user: ohdsi

ingress:
  host: ${dns_prefix}odhsi.${private_dnz_zone}
  annotations:
    xlscsde.nhs.uk/dns-record: ohdsi
  tls:
    enabled: true
    secretName: ${dns_prefix}odhsi.${private_dnz_zone}-tls
