atlas:
  image: lscsde/ohdsi-atlas-base:0.1.0
  env:
  - name: USER_AUTHENTICATION
    value: "true"
  
  - name: OID_PROVIDER_ENABLED
    value: "true"

  - name: SUPPORT_MAIL
    value: "shaun.turner1@nhs.net"

  - name: APP_NAME
    value: "LSCSDE - OHDSI Atlas"

flyway:
  datasource:
    hostname: "${postgresql_server}"
    port: "5432"
    database: ohdsi
    user: "ohdsi@${postgresql_server}"

webapi:
  truststore:
    path: /usr/local/openjdk-8/lib/security/cacerts
  volumes:
  - name: truststore-volume
    configMap:
      name: keycloak-certificate-authority
      items:
      - key: keycloak.jks
        path: cacerts

  volumeMounts:
  - mountPath: /usr/local/openjdk-8/lib/security/cacerts
    subPath: cacerts
    name: truststore-volume
    readOnly: true
  

datasource:
  hostname: "${postgresql_server}"
  port: "5432"
  database: ohdsi
  user: "ohdsi@${postgresql_server}"

security:
  provider: "" #"AtlasRegularSecurity"
  oauth:
    callback:
      urlResolver: ""
      api: https://${dns_prefix}ohdsi.${private_dnz_zone}/WebAPI/user/oauth/callback
      ui: "https://${dns_prefix}ohdsi.${private_dnz_zone}/atlas/#/welcome"
  oid:
    enabled: true
    clientId: "ohdsi"
    apiSecret:
      secretName: "ohdsi"
      key: "ohdsi-client-secret"
    url: "https://${dns_prefix}keycloak.${private_dnz_zone}/realms/lsc-sde/.well-known/openid-configuration"
    redirectUrl: "https://${dns_prefix}ohdsi.${private_dnz_zone}/atlas/#/welcome"

ingress:
  host: ${dns_prefix}ohdsi.${private_dnz_zone}
  annotations:
    xlscsde.nhs.uk/dns-record: ohdsi
    nginx.ingress.kubernetes.io/ssl-redirect : "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect : "true"
  tls:
    enabled: true
    secretName: ${dns_prefix}ohdsi.${private_dnz_zone}-tls
