atlas:
  image: lscsde/ohdsi-atlas-base:0.1.1
  env:
  - name: USE_DYNAMIC_WEBAPI_URL
    value: "true"

  - name: ATLAS_USER_AUTH_ENABLED
    value: "true"
  
  - name: ATLAS_SECURITY_OID_PROVIDER_ENABLED
    value: "true"

  - name: ATLAS_SUPPORT_MAIL
    value: "shaun.turner1@nhs.net"

  - name: ATLAS_INSTANCE_NAME
    value: "LSCSDE - OHDSI Atlas"

  - name: ATLAS_CLEAR_LOCAL_STORAGE
    value: "true"

  - name: ATLAS_SECURITY_OID_PROVIDER_NAME
    value: "Microsoft Entra ID"

  - name: ATLAS_SECURITY_PROVIDER_ENABLED
    value: "false"

flyway:
  datasource:
    hostname: "${postgresql_server}"
    port: "5432"
    database: ohdsi
    user: "ohdsi@${postgresql_server}"

webapi:
  image: ohdsi/webapi:2.14.0
  security:
    db:
      datasource:
        schema: "webapi_security"
        url: "jdbc:postgresql://${postgresql_server}:5432/ohdsi"
        driverClassName: "org.postgresql.Driver"
        username: "ohdsi@${postgresql_server}"
        password:
          secret: "ohdsi"
          key: "db-password"
  # truststore:
  #   path: /usr/local/openjdk-8/lib/security/cacerts
  # volumes:
  # - name: truststore-volume
  #   configMap:
  #     name: keycloak-certificate-authority
  #     items:
  #     - key: keycloak.jks
  #       path: cacerts

  # volumeMounts:
  # - mountPath: /usr/local/openjdk-8/lib/security/cacerts
  #   subPath: cacerts
  #   name: truststore-volume
  #   readOnly: true
  

datasource:
  hostname: "${postgresql_server}"
  port: "5432"
  database: ohdsi
  user: "ohdsi@${postgresql_server}"

security:
  shiro:
    successUrl: https://${dns_prefix}ohdsi.${private_dnz_zone}/WebAPI/user/login/openid?redirectUrl=/home
  provider: "AtlasRegularSecurity"
  oauth:
    callback:
      #urlResolver: ""
      api: https://${dns_prefix}ohdsi.${private_dnz_zone}/WebAPI/user/oauth/callback
      ui: "https://${dns_prefix}ohdsi.${private_dnz_zone}/atlas/#/welcome"
  oid:
    enabled: true
    clientId: "${ohdsi_client_id}"
    apiSecret:
      secretName: "ohdsi"
      key: "ohdsi-appreg-client-secret"
    url: "https://login.microsoftonline.com/f12f0279-8a84-4068-8322-7a6fb0f839b8/v2.0/.well-known/openid-configuration"
    redirectUrl: "https://${dns_prefix}ohdsi.${private_dnz_zone}/atlas/#/welcome"

ingress:
  host: ${dns_prefix}ohdsi.${private_dnz_zone}
  annotations:
    xlscsde.nhs.uk/dns-record: ohdsi
    nginx.ingress.kubernetes.io/ssl-redirect : "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect : "true"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://${dns_prefix}ohdsi.${private_dnz_zone}:8080"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://${dns_prefix}ohdsi.${private_dnz_zone}"

  tls:
    enabled: true
    secretName: ${dns_prefix}ohdsi.${private_dnz_zone}-tls
