flyway:
  datasource:
    hostname: "${postgresql_host}"
    port: "5432"
    database: "${ohdsi_database}"
    user: "${ohdsi_user}"

datasource:
  hostname: "${postgresql_host}"
  port: "5432"
  database: "${ohdsi_database}"
  user: "${ohdsi_user}"

ingress:
  host: ${dns_prefix}odhsi.${private_dnz_zone}
  tls:
    enabled: true
    secretName: ${dns_prefix}odhsi.${private_dnz_zone}-tls
