flyway:
  datasource:
    hostname: "${postgresql_server}"
    port: "5432"
    database: ohdsi
    user: "ohdsi@${postgresql_server}"

datasource:
  hostname: "${postgresql_server}"
  port: "5432"
  database: ohdsi
  user: "ohdsi@${postgresql_server}"

security:
  provider: "AtlasRegularSecurity"
  oid:
    clientId: "ohdsi"
    apiSecret:
      secretName: "ohdsi"
      key: "ohdsi-client-secret"
    url: "https://${dns_prefix}keycloak.${private_dnz_zone}/realms/lsc-sde/.well-known/openid-configuration"
    redirectUrl: "https://${dns_prefix}ohdsi.${private_dnz_zone}/atlas/#/welcome"

ingress:
  host: ${dns_prefix}ohdsi.${private_dnz_zone}
  annotations:
    xlscsde.nhs.uk/dns-record: ohdsi
    nginx.ingress.kubernetes.io/ssl-redirect : "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect : "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  tls:
    enabled: true
    secretName: ${dns_prefix}ohdsi.${private_dnz_zone}-tls
