apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${ohdsi_namespace}
resources:
- release.yaml
- repository.yaml
- secret.yaml
- networkpolicy.yaml
configMapGenerator:
  - name: environment-config
    files:
      - values.yaml=environment-config.yaml
generatorOptions:
  disableNameSuffixHash: true