apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ohdsi
  namespace: ohdsi
  annotations:
    xlscsde.nhs.uk/flux-branch: ${ohdsi_branch}
spec:
  targetNamespace: ohdsi
  releaseName: ohdsi
  chart:
    spec:
      chart: ohdsi
      version: ${ohdsi_chart_version}
      sourceRef:
        kind: HelmRepository
        name: ohdsi
        namespace: ohdsi
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  valuesFrom:
  - kind: ConfigMap
    name: environment-config