apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: ${dns_prefix}ohdsi.${private_dnz_zone}-tls
  annotations:
    xlscsde.nhs.uk/secretUsage: "Wildcard Certificate"
spec:
  name: ${dns_prefix}ohdsi.${private_dnz_zone}-tls
  type: kubernetes.io/tls
  secrets:
  - from: WildcardCertificate
    to: tls.crt
  - from: WildcardCertificateKey
    to: tls.key
---
apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: odhsi
  annotations:
    xlscsde.nhs.uk/secretUsage: "OHDSI passwords"
spec:
  name: ohdsi
  secrets:
  - from: OhdsiDbPassword
    to: db-password
    
  - from: HadesPassword
    to: hades-password