apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-certificate-authority
spec:
  isCA: true
  commonName: keycloak local certificate
  secretName: keycloak-certificate-authority-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: sde
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: keycloak-certificate-authority
spec:
  ca:
    secretName: keycloak-certificate-authority-tls
    